# Generated by Django 3.0.2 on 2020-02-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200229_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subject',
            new_name='slug',
        ),
    ]
